Training:
  N_EPOCHS: 50
  LEARNING_RATE: 3.0e-4
  BATCH_SIZE: 8
  IMAGE_SIZE: [ 256, 256 ]
  NUM_WORKERS: 0
  SEED: 42

Dirs:
  TRAIN_DIR: "./data/train"
  VAL_DIR: "./data/val"
  TEST_DIR: "./data/test"
  LOG_DIR: "./logs"
  MODEL_SAVE_DIR: "./bin"

WANDB_PROJECT: "cancer-cell-segmentation"
